### ISSUE TITLE
FOSS (Free and open-source software) or proprietary

### ISSUE THREAD

**Issue by Domosed-gamin** [codesmith-fi/saladir#1]
Which license? Is this game FOSS (Free and open-source software) or proprietary? If it is FOSS, please put good license file like GPL, MIT or similar.

https://en.wikipedia.org/wiki/Free_and_open-source_software

**Comment by codesmith-fi** [comment]
It's free so I suppose MIT will be good, but you can go with MIT
I'll try to add it later.

**Comment by Domosed-gamin** [comment]
Nice. Thank you for license.
